#!/usr/bin/env python3
"""Target-level bootstrap intervals for crossed 2x2 OOF predictions.

Repeated-CV predictions are averaged for each target before resampling.  The
bootstrap therefore treats targets, rather than CV repeats, as the independent
sampling units.  It reports AUC, AUC minus chance, and an equivalence decision
for the prespecified |AUC - 0.5| < margin region.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

from reviewer_followup.common import atomic_write_csv, atomic_write_json, base_manifest, sha256_file


REQUIRED = {"comparison", "method", "repeat", "sample_id", "y_true", "score"}


def average_target_scores(frame: pd.DataFrame) -> pd.DataFrame:
    missing = REQUIRED - set(frame.columns)
    if missing:
        raise ValueError(f"Prediction CSV missing columns: {sorted(missing)}")
    work = frame.copy()
    work["y_true"] = pd.to_numeric(work["y_true"], errors="raise").astype(int)
    work["score"] = pd.to_numeric(work["score"], errors="raise")
    if work.duplicated(["comparison", "method", "repeat", "sample_id"]).any():
        raise ValueError("Duplicate comparison/method/repeat/sample_id predictions")
    inconsistent = work.groupby(["comparison", "method", "sample_id"])["y_true"].nunique()
    if (inconsistent > 1).any():
        raise ValueError("A target changes label across CV repeats")
    return (
        work.groupby(["comparison", "method", "sample_id", "y_true"], as_index=False)
        .agg(score=("score", "mean"), n_repeats=("repeat", "nunique"))
    )


def bootstrap_auc_rows(
    averaged: pd.DataFrame,
    *,
    source: str,
    n_bootstrap: int = 10_000,
    seed: int = 42,
    margin: float = 0.05,
) -> pd.DataFrame:
    if not 0 < margin < 0.5:
        raise ValueError("equivalence margin must lie in (0, 0.5)")
    rows: list[dict[str, object]] = []
    for group_index, ((comparison, method), part) in enumerate(
        averaged.groupby(["comparison", "method"], sort=True)
    ):
        y = part["y_true"].to_numpy(int)
        score = part["score"].to_numpy(float)
        pos = np.flatnonzero(y == 1)
        neg = np.flatnonzero(y == 0)
        if not len(pos) or not len(neg):
            raise ValueError(f"{comparison}/{method} does not contain both classes")
        rng = np.random.default_rng(seed + group_index)
        values = np.empty(n_bootstrap, dtype=float)
        for index in range(n_bootstrap):
            sampled = np.concatenate(
                [rng.choice(pos, len(pos), replace=True), rng.choice(neg, len(neg), replace=True)]
            )
            values[index] = roc_auc_score(y[sampled], score[sampled])
        point = float(roc_auc_score(y, score))
        low, high = np.quantile(values, [0.025, 0.975])
        difference_low, difference_high = float(low - 0.5), float(high - 0.5)
        if difference_low > 0:
            chance_class = "above_chance"
        elif difference_high < 0:
            chance_class = "below_chance"
        else:
            chance_class = "inconclusive_vs_chance"
        equivalent = bool(difference_low > -margin and difference_high < margin)
        rows.append(
            {
                "source": source,
                "comparison": comparison,
                "method": method,
                "n_targets": int(len(part)),
                "n_positive": int(len(pos)),
                "n_negative": int(len(neg)),
                "n_repeats_min": int(part["n_repeats"].min()),
                "n_repeats_max": int(part["n_repeats"].max()),
                "auc": point,
                "auc_ci_low": float(low),
                "auc_ci_high": float(high),
                "auc_minus_chance": point - 0.5,
                "auc_minus_chance_ci_low": difference_low,
                "auc_minus_chance_ci_high": difference_high,
                "equivalence_margin": margin,
                "equivalent_to_chance": equivalent,
                "chance_classification": "equivalent_to_chance" if equivalent else chance_class,
                "n_bootstrap": n_bootstrap,
            }
        )
    return pd.DataFrame(rows)


def latex_rows(frame: pd.DataFrame) -> str:
    lines = [
        "% Generated by reviewer_followup.analyze_factorial_uncertainty.",
        "% Construct & contrast & AUC [95\\% target-bootstrap CI] & chance decision \\\\",
    ]
    for row in frame.itertuples(index=False):
        source = str(row.source).replace("_", "\\_")
        comparison = str(row.comparison).replace("_", "\\_")
        decision = str(row.chance_classification).replace("_", " ")
        lines.append(
            f"{source} & {comparison} & {row.auc:.3f} "
            f"[{row.auc_ci_low:.3f}, {row.auc_ci_high:.3f}] & {decision} \\\\"
        )
    return "\n".join(lines) + "\n"


def parse_input(value: str) -> tuple[str, Path]:
    if "=" not in value:
        raise ValueError(f"Expected LABEL=CSV, got {value}")
    label, path = value.split("=", 1)
    if not label or not path:
        raise ValueError(f"Expected LABEL=CSV, got {value}")
    return label, Path(path)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", action="append", required=True, help="LABEL=factorial_outer_predictions.csv")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--n-bootstrap", type=int, default=10_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--equivalence-margin", type=float, default=0.05)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    inputs = dict(parse_input(value) for value in args.input)
    if len(inputs) != len(args.input):
        raise ValueError("Input labels must be unique")
    result = []
    averaged = []
    for offset, (label, path) in enumerate(sorted(inputs.items())):
        target_scores = average_target_scores(pd.read_csv(path))
        target_scores.insert(0, "source", label)
        averaged.append(target_scores)
        result.append(
            bootstrap_auc_rows(
                target_scores.drop(columns="source"),
                source=label,
                n_bootstrap=args.n_bootstrap,
                seed=args.seed + offset * 100_000,
                margin=args.equivalence_margin,
            )
        )
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    result_frame = pd.concat(result, ignore_index=True)
    averaged_frame = pd.concat(averaged, ignore_index=True)
    atomic_write_csv(output / "factorial_target_bootstrap.csv", result_frame)
    atomic_write_csv(output / "factorial_target_averaged_predictions.csv", averaged_frame)
    (output / "factorial_target_bootstrap_rows.tex").write_text(latex_rows(result_frame), encoding="utf-8")
    manifest = base_manifest(experiment="reviewer_revision_factorial_uncertainty", command=sys.argv)
    manifest.update(
        {
            "status": "completed",
            "resampling_unit": "target_after_averaging_repeated_cv_scores",
            "n_bootstrap": args.n_bootstrap,
            "seed": args.seed,
            "equivalence_margin": args.equivalence_margin,
            "inputs": {label: {"path": str(path), "sha256": sha256_file(path)} for label, path in inputs.items()},
        }
    )
    atomic_write_json(output / "factorial_uncertainty_manifest.json", manifest)
    print(result_frame.to_string(index=False))


if __name__ == "__main__":
    main(sys.argv[1:])
